services:
  kafka:
    image: ${KAFKA_IMAGE}
    container_name: kafka
    networks:
      - redecor-net
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    healthcheck:
      test: ["CMD", "/opt/kafka/bin/kafka-topics.sh", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: ${POSTGRES_IMAGE}
    container_name: postgres
    networks:
      - redecor-net
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    networks:
      - redecor-net
    ports:
      - "${KAFKA_UI_PORT}:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092

  prometheus:
    image: ${PROMETHEUS_IMAGE}
    container_name: prometheus
    user: root
    networks:
      - redecor-net
    ports:
      - "${PROMETHEUS_PORT}:9090"
    volumes:
      - ./observability/prometheus.yml:/etc/prometheus/prometheus.yml:Z
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - kafka
      - postgres

  grafana:
    image: ${GRAFANA_IMAGE}
    container_name: grafana
    networks:
      - redecor-net
    ports:
      - "${GRAFANA_PORT}:3000"
    volumes:
      - ./observability/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:Z
      - ./observability/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:Z
      - ./observability/grafana/dashboards:/etc/grafana/dashboards:Z
    depends_on:
      - prometheus

networks:
  redecor-net:
    name: redecor-net
    driver: bridge
