FROM python:3.11-slim

RUN apt-get update && apt-get install -y docker.io && rm -rf /var/lib/apt/lists/*
RUN pip install requests

WORKDIR /app
COPY autoscale.py .

CMD ["python", "-u", "autoscale.py"]
