{
 "title": "Visibilidade de Extracoes",
 "tags": [
  "Devops",
  "SRE"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Extracoes por Segundo (OK)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (instance) (rate(extraction_processed_total[1m]))"
    }
   ]
  },
  {
   "title": "Total de Falhas",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(extraction_failure_total)" }
   ]
  },
  {
   "title": "Ritmo de Ingestao (Producer)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (instance) (rate(extraction_sent_total[1m]))"
    }
   ]
  }
 ]
}